spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: root

    
  mail:
    host: smtp.gmail.com
    port: 587
    username: nsgarafaite@gmail.com
    password: nehruian
    protocol: smtp
    tls: true
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com
      
    
    
    
camel:
  springboot:
    shutdown-timeout: 2
  health:
    check:
      routes:
        enabled: true